[package]
name = "aios-database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sea-query = { path = "/Volumes/DPC/workspace/sea-query" }
config = "0.13.1"
bincode = "1.3.3"
anyhow = "1.0.57"
serde_json = "1.0.81"
hex = "0.4.3"
futures = "0.3.21"
smol_str = "0.1.23"
itertools = "0.10.3"
lazy_static = "1.4.0"
async-trait = "0.1.52"
dotenv = "0.15.0"

parse_pdms_db = { path = "../aios-parse-pdms" }
aios_core = { path =  "../aios_core"}

clap = { version = "3.1.18", features = ["derive"] }
dashmap = { version = "5.2.0", features = ["serde"] }
tokio = { vertion = "1.18.2", features = ["full"] }
serde = {version="1.0.137", features=["derive"]}
id_tree = { version = "1.8.0", features = ["serde_support"] }
glam = { version = "0.20.2", features = ["transform-types"] }
sea-orm = { version = "0.8.0", features = ["default", "runtime-tokio"]}


[dependencies.sqlx]
version = "^0.5"
default-features = false
features = [
    "runtime-async-std-native-tls",
    "macros",
    "mysql",
    "tls",
    "chrono",
    "json",
    "decimal",
    "bigdecimal",
    "uuid",
    "time",
]