total_sync = true
incr_sync = false
#project_path = "E:/AVEVA/Plant/Projects12.1.SP4"
project_path = "E:/pdms_data_files"
included_projects = ["Sample"]
#included_projects = ["SCB","ZNP"]
mdb_name = "Sample"
project_name = "Sample"
main_db_code = 7200
ip = "127.0.0.1"
user = "root"
password = "root"
port = "3306"