#同步文件配置
total_sync = true
enable_log = false
sync_graph_db = true
sync_tidb = true
incr_sync = false
replace_dbs = false

#项目设置
project_path = "/Users/dongpengcheng/Documents/models/e3d_models" #TestCatalogue
included_projects = ["AvevaMarineSample" , "AvevaCatalogue", "SCB", "ZDJ"]
#included_projects = ["AvevaCatalogue"]  #"AvevaPlantSample",
#included_projects = ["AvevaMarineSample"]  #"AvevaPlantSample",

mdb_name = "ALL"
project_name = "AvevaMarineSample"
module = "DESI"
gen_model_mesh = true
gen_spatial_tree = false
save_spatial_tree_to_db = false
gen_model_batch_size = 100

#arangodb 配置
arangodb_database = "ams"
multi_threads = true
only_sync_sys = false
arangodb_url = "http://127.0.0.1:8529"
rebuild_ssc_tree = false
arangodb_user = "root"
arangodb_password = ""

#tidb 配置
ip = "127.0.0.1"
user = "root"
password = ""
#port = "3306"
port = "4000"
sql_threads_number = 50
batch_insert_sql_cnt = 500   #mysql 批量插入的数量

#服务器启动配置
server_release_ip = "127.0.0.1:9099"


#调试选项
replace_mesh = true
save_model_mesh_to_graph_db = true
need_sync_refno_basic = false  #是否重新生成 refno_basic 缓存
reset_mdb_project = false      #是否重新生成 mdb 缓存
only_update_dbinfo = false
debug_print_world_transform = false
only_rebuild_pdms_element = false

debug_refno_types = ["CATA", "LOOP", "PRIM"]
included_db_files = ["ams1112_0001"]
#included_db_files = ["acp7001_0001"]
manual_db_nums = [7999, 7997, 1112, 8000]
#manual_db_nums = [1112]  #, 8000
plat_url = ""

#joint还有问题，方位对齐的问题
#debug_root_refnos = ["23708/26027"]


#管道不出来的情况，需要查一下原因, *以解决
#debug_root_refnos = ["24381/57428"]

#debug_root_refnos = ["9304/2"]
#拉伸体的wire共线的问题, 开门洞还是有问题需要调试
#debug_root_refnos = ["17496/106258"]

#生成会崩溃, 已解决
#debug_root_refnos = ["24383/73928"]

#房间计算用
#debug_root_refnos = ["24381/34848"]

#风管还有问题
#debug_root_refnos = ["24381/57479"]

#风管有问题  还剩下OF的计算没有解决
#debug_root_refnos = ["24381/57478"]
#风管的rtorus 生成有问题
#debug_root_refnos = ["24381/57524"]

#桥架有问题 *已解决
#debug_root_refnos = ["24384/22404"]

#楼板生成有问题, 需要offset，这里判断如果是extrusion，就需要offset
#debug_root_refnos = ["24381/40192"]
#debug_root_refnos = ["24381/40451"]

#debug_root_refnos = ["24384/24932"]

#生成的负实体，没有将圆柱体削成半球
#debug_root_refnos = ["24381/36945"]

#debug_root_refnos = ["24383/73985"]

#Cut 崩溃, 需要一个个切
#debug_root_refnos = ["24381/57864"]

#Cut 崩溃, 被offset影响
#debug_root_refnos = ["24383/78369"]

#debug_root_refnos = ["24383/76668"]


#transform 有不合适的值，NAN
#debug_root_refnos = ["24381/105513"]

#stwall的元件库生成模型有错误
#debug_root_refnos = ["17496/106397"]

#24381_105593

#debug_root_refnos = ["17496/167201"]
#debug_root_refnos = ["17496/169950"]

#指定哪些根节点下面是房间，以FRMW为一个整体
room_root_refnos = ["24381/35538", "24381/35622"]

#room_root_refnos = ["24381/35622"]
#24381_105593\




