total_sync = true
incr_sync = false
project_path = "E:/AVEVA/Plant/Projects12.1.SP4"
included_projects = ["Sample"]
#included_projects = ["SCB","ZNP"]
mdb_name = "Sample"
project_name = "Sample"
main_db_code = 7200
sql_threads_number = 500
batch_insert_sql_cnt = 1
files_multi_thread = true
types_multi_thread = true
ip = "127.0.0.1"
user = "root"
password = "root"
port = "3306"