use std::collections::BTreeMap;
use std::env;
use aios_core::pdms_types::{AiosStr, AttrInfo, AttrMap, AttrVal, DbAttributeType, NounHash, RefU64};
use anyhow::anyhow;
use dashmap::DashMap;
use parse_pdms_db::db1_dehash;
use parse_pdms_db::db_tool::db1_hash;
use smol_str::SmolStr;
use sqlx::{MySql, Pool, Row};
use crate::api::{attr, element};
use crate::api::element::{query_children, query_pdms_elements_type_name, query_project_name};
use crate::consts::PDMS_INFO_DB;
use crate::data_interface::tidb_manager::AiosDBManager;
use crate::REFNO_INFO_MAP;
use crate::sql::gen_sql::*;