use std::collections::HashMap;
use aios_core::pdms_types::{AttrInfo, AttrMap, AttrVal, NounHash, RefU64, RefU64Vec};
use dashmap::DashMap;
use parse_pdms_db::db1_dehash;
use parse_pdms_db::db_tool::db1_hash;
use parse_pdms_db::parse::WholeAttMap;
use smol_str::SmolStr;
use sqlx::Executor;
use sqlx::{MySql, Pool};
use crate::REFNO_INFO_MAP;